In [1]:
import numpy as np
import time

#  Contracciones tensoriales y problemas de valores propios

En el desarollo de la química cuantica para estructura electrónica, uno comunmente se encuentra con
problemas de valores propios y manipulación de tensores multidimensionales. Eso se debe a 
la utilización de bases monoelectrónicas para la construcción de una función de onda multielectrónica. 

Para facilitar la escritura de las contracciones tensoriales, se emplea la llamada notación de einstein 
en la cuál la está implicita la sumatorio sobre indices repetidos. En una multiplicación matricial por ejemplo
las dos notaciones distintas son:

\begin{align} 
\rm{Convencional:}\;\;\; C_{ik} &= \sum_{j} A_{ij} * B_{jk} \\ \rm{Einstein:}\;\;\; C_{ik} &= A_{ij} * B_{jk} \ 
\end{align}

O en notación matricial:

 \begin{align} {\rm Matrix}\;\;\; \bf{D} &= \bf{A B C} \\ {\rm Einstein}\;\;\; D_{il} &= A_{ij} B_{jk} C_{kl} \end{align}

Numpy tiene dos funciones que permiten calcular productos entre matriciesm que son np.dot y np.einsum. 
Por ejemplo dado dos matrices **I** y **J** de 2x2, se puede calcular el producto utilizando el método np.dot:

In [2]:
size = 2
I = np.random.rand(size, size)
J = np.random.rand(size, size)

DI = np.dot(I,J)
print DI

[[ 0.17468709  0.0356804 ]
 [ 0.42868182  0.20007084]]


O tambíen utilizando las sumatorias de einstein np.einsum

In [3]:
DI_ein = np.einsum('ik,kj',I,J)
print DI_ein

[[ 0.17468709  0.0356804 ]
 [ 0.42868182  0.20007084]]


Notese que en la notación del metodo einsum los indices solamente indican la regla de la contracción.

## Ejercicio 1: 
Escriba una rutina que contrae tensores dos dimensionales y verifique el funcionamiento de su rutina con 
los métodos descritos anteriormente:

In [4]:
A = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]])
B = np.array([[1.0,2.0,9.0],[4.0,6.0,6.0],[1.5,0.0,9.8]])

print A
print B

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
[[ 1.   2.   9. ]
 [ 4.   6.   6. ]
 [ 1.5  0.   9.8]]


In [33]:
AB = np.zeros((3,3))

for i in range(len(A)):
    for j in range(len(B)):
        for k in range(len(B)):
            AB[i][j]= AB[i][j]+ A[i][k]*B[k][j]
print

In [35]:
print AB


[[  13.5   14.    50.4]
 [  33.    38.   124.8]
 [  52.5   62.   199.2]]


In [36]:
X=np.dot(A,B)
print X

[[  13.5   14.    50.4]
 [  33.    38.   124.8]
 [  52.5   62.   199.2]]


In [37]:
X_ein = np.einsum('ik,kj',A,B)
print X_ein

[[  13.5   14.    50.4]
 [  33.    38.   124.8]
 [  52.5   62.   199.2]]


# Ejercicio 2
Un paso clave en el método Hartree-Fock es la construcción de la matrix de Fock: 
En notación de einstein se construye utilizando la siguiente contracción de tensores:

\begin{equation}
G_{pq} = 2I_{pqrs}D_{rs} - I_{prqs}D_{rs}  
\end{equation}

Donde $I_{pqrs}$ es un tensor de integrales de repulsion electrónica. Defina dos tensores aleatorios **D** y **I** 
y calcule la contracción indicada. Verifíque su resultado mediante el método np.einsum

In [40]:
size = 4
D = np.random.rand(size, size)
I = np.random.rand(size, size, size, size)
G = np.zeros((size,size))

In [43]:
print D
print I
print G

[[ 0.38416078  0.61909769  0.32455055  0.00747794]
 [ 0.67539232  0.18683269  0.04411163  0.81314422]
 [ 0.78802491  0.64376786  0.47825452  0.7721874 ]
 [ 0.99528296  0.39206245  0.25784222  0.04767374]]
[[[[  5.04509171e-01   6.91605013e-01   6.17920176e-01   3.75169639e-01]
   [  1.49814016e-01   4.25021620e-01   4.17597946e-01   6.51488529e-01]
   [  3.11145122e-01   7.24239400e-01   2.56199923e-01   9.85296769e-01]
   [  1.52450101e-01   2.37545250e-01   4.76663766e-01   8.34608955e-01]]

  [[  9.27941423e-01   5.25142930e-01   3.00433959e-02   1.95297513e-01]
   [  7.88916901e-01   1.38672216e-01   2.45660775e-01   8.85013350e-01]
   [  1.39849010e-01   5.44624919e-01   4.32931156e-01   1.84700050e-01]
   [  2.93892220e-01   7.28393072e-01   9.25716679e-01   2.50417660e-01]]

  [[  3.83934705e-01   6.13048724e-02   7.16597382e-01   7.50060286e-01]
   [  1.97832997e-01   3.61833996e-01   3.19761601e-01   4.47130063e-01]
   [  3.91736664e-01   4.69831757e-01   9.51259188e-01   2.31

In [56]:
for p in range(len(I)):
    for q in range(len(I)):
            for r in range(len(D)):
                for s in range(len(D)):
                    G[p][q]= G[p][q] + 2*I[p][q][r][s] * D[r][s]
                    G[p][q]= G[p][q] - I[p][r][q][s]* D[r][s]
print G

[[ 14.10286029  15.00801662  15.41135977  13.61183314]
 [ 14.7921484   15.18354997  15.94590034  14.90638906]
 [ 11.37385734  20.5956344    8.33021393  19.47773118]
 [ 10.16368871  23.52501929  15.02612096  16.14387206]]


In [60]:
X_1=np.einsum('pqrs,rs',I,D)
X_2=np.einsum('prqs,rs',I,D)
X_3 = 2*X_1 - X_2
print X_3

[[ 3.49497719  3.88278737  4.17343199  3.31914905]
 [ 3.86098789  3.74590404  4.13388042  3.88933041]
 [ 2.39505199  5.54490746  1.59391972  5.55088647]
 [ 1.96913602  6.53262285  3.71573104  4.02970646]]


# Problema de valor propio 


El problema de valores propios está en el corazon de la química quántica. En este ejercicio vamos a encontrar 
los valores y vectores propios de una matriz hermítica, como por ejemplo la matriz hamiltoniana en 
una base finita que aparece en su tarea. 

En general el la ecuación de valores propios para un operador $\mathbf{O}$ $N\times N$ se expresa como:

\begin{equation}
\mathbf{O}\mathbf{c} = \omega\mathbf{c}
\end{equation}

Aquí $\mathbf{c}$ es un vector en una base $N$-dimensional
Esta ecuación se puede reescribir como:

\begin{equation}
(\mathbf{O} - \omega\mathbf{1})\mathbf{c} = 0
\end{equation}

Este problema tiene soluciones no triviales solo cuando 

\begin{equation}
|\mathbf{O} - \omega\mathbf{1}| = 0
\end{equation}

Es determinante se detnomina determinante secular y es un polinomio de grado N, por lo 
que tiene N raices de $\omega_{\alpha}$, que serian los valores propios de la matriz. 
Los vecotres propios se obtienen al resolver el sistema de ecuaciones:

\begin{equation}
\mathbf{O}\mathbf{c^{\alpha}} = \omega_{\alpha}\mathbf{c^{\alpha}} \qquad \alpha = 1,2,..., N
\end{equation}


Para un operador hermítico la matriz compuesta por los vectores propios $\mathbf{U}$ es una matriz unitaria que 
diagonaliza al operador en su base no diagonal:

\begin{equation}
\mathbf{\omega} = \mathbf{U^{\dagger}}\mathbf{O}\mathbf{U} 
\end{equation}


# Ejercicio 3

Encuentre los valores y vectores propios de una matriz de dimensiones 4x4 con el método descrito anteriormente y utilizando la rutina numpy.linalg.eig. (Hint: Use el metodo charpoly() implementada en symmpy)

In [4]:
## Construir Matriz diagonal
H_tmp = np.random.rand(4, 4)
H = (H_tmp + H_tmp.T)/2
print H

[[ 0.87765091  0.70886773  0.53246895  0.48171192]
 [ 0.70886773  0.54466747  0.4174548   0.61151929]
 [ 0.53246895  0.4174548   0.75080152  0.71581245]
 [ 0.48171192  0.61151929  0.71581245  0.93187373]]
